### ISSUE TITLE
Node.jsとryosk7/mybase imageを使ったdocker-compose.ymlはどのように書けばいいですか？

### ISSUE THREAD

**Issue by ryosk7** [ryosk7/my_base_docker_image#1]
### volumeを設定してマウントをしたいんですが、うまく起動してくれません。
Dockerfile
```Dockerfile
FROM ryosk7/mybase:debian-jessie
CMD ["bin/bash"]
RUN curl -SL https://deb.nodesource.com/setup_11.x | bash
RUN apt-get install -y nodejs
RUN npm install -g vue-cli
ENV HOST 0.0.0.0
EXPOSE 3000
```
docker-compose.yml
```yml
version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - "$PWD:/app"
    ports:
      - "3000:3000"
```

**Comment by ryosk7** [comment]
## 解決 
Dockerfile
```dockerfile
FROM node:10.15.3-jessie
RUN npm install -g vue-cli
WORKDIR /app
ENV HOST 0.0.0.0
EXPOSE 3000
USER node
COPY --chown=node:node . WORKDIR
```
docker-compose.yml
```yml
version: '3'
services:
  app:
    build: .
    user: "${UID}:${GID}"
    tty: true
    volumes:
      - "$PWD:/app"
    ports:
      - "3000:3000"
```
として、コンテナ内で生成されたファイルに対して、
ローカル上のshellで
```sh
sudo chown -R $USER:$USER .
```
を叩くことで、ファイルの所有権をuserに変更できる。
